name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js for frontend
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install frontend dependencies
      working-directory: ./frontend/signboard
      run: npm install

    - name: Run frontend tests
      working-directory: ./frontend/signboard
      run: npm test

    - name: Build frontend
      working-directory: ./frontend/signboard
      run: npm run build

    - name: Setup Node.js for backend
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install backend dependencies
      working-directory: ./backend/signboard
      run: npm install

    - name: Run backend tests
      working-directory: ./backend/signboard
      run: npm test

    - name: Build backend
      working-directory: ./backend/signboard
      run: npm run build
